name: CI/CD for telegram_admin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout кода
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Настройка SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    # 3. Установим docker-Compose
    # - name: Install Docker Compose
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y docker-compose
    
    # 5. Создаём файл .env-non-dev из секретов
    - name: Create .env file
      run: echo "${{ secrets.ENV_FILE }}" > ./.env

    # 7. Проверка Docker Compose
    # - name: Lint Docker Compose
    #   run: docker-compose -f docker-compose.yml config

    # 8. Сборка Docker образов
    - name: Build Docker image
      run: |
        docker build .

    # 9. Копирование файлов на сервер
    - name: Deploy files to server
      run: |
        ssh -o StrictHostKeyChecking=no los@176.123.167.12 "mkdir -p ~/bot_admin"
        rsync -avz --exclude=".git" ./ los@176.123.167.12:~/bot_admin/

    # 10. Запуск Docker Compose на сервере
    - name: Restart application
      run: |
        ssh -o StrictHostKeyChecking=no los@176.123.167.12 << 'EOF'
          cd ~/bot_admin
          sudo docker stop telegram_admin_container
          sudo docker rm telegram_admin_container
          sudo docker image rm telegram_admin
          sudo docker build -t telegram_admin .
          sudo docker run --name telegram_admin_container telegram_admin 
        EOF
